/* Generated by AN DISI Unibo */ 
package it.unibo.led

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Led ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "off"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
				val name = "LedActor"	
		return { //this:ActionBasciFsm
				state("off") { //this:State
					action { //it:State
						println("	$name: OFF")
					}
					 transition(edgeName="t00",targetState="blink",cond=whenEvent("robotMoving"))
				}	 
				state("on") { //this:State
					action { //it:State
						println("	$name: ON")
					}
					 transition(edgeName="t31",targetState="blink",cond=whenEvent("robotMoving"))
				}	 
				state("blink") { //this:State
					action { //it:State
						println("	$name: BLINK!")
					}
					 transition(edgeName="t12",targetState="off",cond=whenEvent("robotAtHome"))
					transition(edgeName="t13",targetState="on",cond=whenEvent("robotStopped"))
				}	 
			}
		}
}
