/* Generated by AN DISI Unibo */ 
package it.unibo.led

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Led ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		
				val name = "LedActor"
				val version = "V1.0"
		
				var ledState = "LedOff"
				
				val runtime = Runtime.getRuntime()
		
				val rasp = false
				
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outred("	 $name: Started! $version")
						updateResourceRep( "started"  
						)
						updateResourceRep( "ledState($ledState)"  
						)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="handleLedStateUpdate", cond=doswitch() )
				}	 
				state("handleLedStateUpdate") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("state(STATE)"), Term.createTerm("state(STATE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 ledState = payloadArg(0)  
								CommUtils.outred("	 $name: Led state - $ledState")
								updateResourceRep( "ledState($ledState)"  
								)
						}
						if(  ledState == "LedOff" && rasp  
						 ){ runtime.exec("sudo bash led25GpioTurnOff.sh")  
						}
						if(  ledState == "LedBlink" && rasp  
						 ){ runtime.exec("sudo bash led25GpioTurnOn.sh")  
						delay(100) 
						 runtime.exec("sudo bash led25GpioTurnOff.sh")  
						}
						if(  ledState == "LedOn" && rasp  
						 ){ runtime.exec("sudo bash led25GpioTurnOn.sh")  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_handleLedStateUpdate", 
				 	 					  scope, context!!, "local_tout_led_handleLedStateUpdate", 100.toLong() )
					}	 	 
					 transition(edgeName="t00",targetState="handleLedStateUpdate",cond=whenTimeout("local_tout_led_handleLedStateUpdate"))   
					transition(edgeName="t01",targetState="handleLedStateUpdate",cond=whenDispatch("ledStateUpdate"))
				}	 
			}
		}
}
