/* Generated by AN DISI Unibo */ 
package it.unibo.transporttrolley

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Transporttrolley ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
				val name = "TransportTrolley"
				var materialType = ""	
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("	 $name: Started!")
					}
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
				state("waiting") { //this:State
					action { //it:State
						println("	 $name: ready and waiting for pickupRequest!")
					}
					 transition(edgeName="t00",targetState="pickup",cond=whenRequest("pickupReq"))
				}	 
				state("pickup") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("pickupReq(ID,T)"), Term.createTerm("pickupReq(ID,T)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 	
												val ID = payloadArg(0)
												materialType = payloadArg(1)
								println("	 $name: pickupRequest($ID) received!")
								delay(10000) 
								println("	 $name: PickupOK!")
								answer("pickupReq", "pickupOk", "pickupOk($ID)"   )  
						}
					}
					 transition( edgeName="goto",targetState="depositPlastic", cond=doswitchGuarded({ materialType == "plastic"  
					}) )
					transition( edgeName="goto",targetState="depositGlass", cond=doswitchGuarded({! ( materialType == "plastic"  
					) }) )
				}	 
				state("depositPlastic") { //this:State
					action { //it:State
						println("	 $name: Depositing plastic!")
						delay(7000) 
					}
					 transition( edgeName="goto",targetState="goHome", cond=doswitch() )
				}	 
				state("depositGlass") { //this:State
					action { //it:State
						println("	 $name: Depositing glass!")
						delay(7000) 
					}
					 transition( edgeName="goto",targetState="goHome", cond=doswitch() )
				}	 
				state("goHome") { //this:State
					action { //it:State
						println("	 $name: Finished Deposit - Going home")
						delay(7000) 
					}
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
			}
		}
}
