/* Generated by AN DISI Unibo */ 
package it.unibo.smartdevice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Smartdevice ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		
				val name = "SmartDevice"
				val version = "V1.0"
		
				var request_ID = 0
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outyellow("	 $name: Started! $version")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("idle") { //this:State
					action { //it:State
						CommUtils.outyellow("	 $name: Waiting for Truck...")
						 request_ID ++  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_idle", 
				 	 					  scope, context!!, "local_tout_smartdevice_idle", 1000.toLong() )
					}	 	 
					 transition(edgeName="t00",targetState="truckArrived",cond=whenTimeout("local_tout_smartdevice_idle"))   
				}	 
				state("truckArrived") { //this:State
					action { //it:State
						 val ID = request_ID  
						if(  ID.toInt()%3 == 0  
						 ){delay(20000) 
						}
						CommUtils.outblack("	 $name: Truck Arrived!")
						CommUtils.outyellow("	 $name: Sending request -$request_ID-")
						if(  ID.toInt()%2 == 0  
						 ){request("depositRequest", "depositRequest(plastic,10)" ,"wasteservice" )  
						}
						else
						 {request("depositRequest", "depositRequest(glass,8)" ,"wasteservice" )  
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t11",targetState="truckGoAway",cond=whenReply("loadaccept"))
					transition(edgeName="t12",targetState="truckGoAway",cond=whenReply("loadrejecetd"))
				}	 
				state("truckGoAway") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("loadrejecetd(ARG)"), Term.createTerm("loadrejecetd(ARG)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outyellow("	 $name: Carico - $request_ID - Rifiutato!")
						}
						if( checkMsgContent( Term.createTerm("loadaccept(ARG)"), Term.createTerm("loadaccept(ARG)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outyellow("	 $name: Scarico - $request_ID - Completato!")
						}
						CommUtils.outyellow("	 $name: Il Truck può andare!")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_truckGoAway", 
				 	 					  scope, context!!, "local_tout_smartdevice_truckGoAway", 1000.toLong() )
					}	 	 
					 transition(edgeName="t33",targetState="idle",cond=whenTimeout("local_tout_smartdevice_truckGoAway"))   
				}	 
			}
		}
}
