/* Generated by AN DISI Unibo */ 
package it.unibo.led

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Led ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		
				val name = "LedActor"
				val version = "V1.0"
		
				var ledState = "off"
				var robotState = "null"
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outred("	 $name: Started! $version")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="handleRobotStateEvent", cond=doswitch() )
				}	 
				state("handleRobotStateEvent") { //this:State
					action { //it:State
						CommUtils.outred("	 $name: Handling RobotState change!")
						if( checkMsgContent( Term.createTerm("robotStateEvent(STATE)"), Term.createTerm("robotStateEvent(STATE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 robotState = payloadArg(0)  
								if(  robotState == "athome"  
								 ){ ledState = "LedOff"  
								}
								if(  robotState == "moving"  
								 ){ ledState = "LedBlink"  
								}
								if(  robotState == "stopped"  
								 ){ ledState = "LedOn"  
								}
								CommUtils.outred("	 $name: Led state- $ledState")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handleRobotStateEvent",cond=whenEvent("robotStateEvent"))
				}	 
			}
		}
}
